# Generated by Django 5.1.7 on 2025-03-20 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='print_orders/')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('Letter', 'Letter')], default='A4', max_length=10)),
                ('color_mode', models.CharField(choices=[('color', 'Color'), ('black_white', 'Black & White')], default='black_white', max_length=20)),
                ('print_sides', models.CharField(choices=[('single', 'Single-sided'), ('double', 'Double-sided')], default='single', max_length=10)),
                ('binding_option', models.CharField(choices=[('none', 'None'), ('staples', 'Staples'), ('spiral', 'Spiral Binding')], default='none', max_length=10)),
                ('urgency', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=10)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card Payment'), ('upi', 'UPI Payment')], default='cod', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
