# Generated by Django 5.1.7 on 2025-03-20 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_printorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printorder',
            name='files',
        ),
        migrations.AlterField(
            model_name='printorder',
            name='binding_option',
            field=models.CharField(choices=[('staples', 'Staples'), ('spiral', 'Spiral')], max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='color_mode',
            field=models.CharField(choices=[('color', 'Color'), ('black/white', 'Black & White')], max_length=12),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('letter', 'Letter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='print_sides',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=10),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='urgency',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], max_length=10),
        ),
        migrations.CreateModel(
            name='PrintOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='print_orders/')),
                ('print_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.printorder')),
            ],
        ),
    ]
