# Generated by Django 5.1.7 on 2025-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_printorder_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
