# Generated by Django 5.1.7 on 2025-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card Payment'), ('upi', 'UPI Payment')], default='cod', max_length=20),
        ),
    ]
