# Generated by Django 5.1.7 on 2025-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='binding_option',
            field=models.CharField(choices=[('none', 'None'), ('staples', 'Staples'), ('spiral', 'Spiral')], max_length=10),
        ),
    ]
